package pipery

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/viper"
)

// config stores all user-configurable runtime settings after loading defaults,
// YAML config, environment variables, and CLI flags.
type config struct {
	ConfigFile      string
	LogFile         string
	ReplayLogFile   string
	ReplayFiles     []string
	SyslogTarget    string
	SyslogTag       string
	QueueSize       int
	MaxCaptureBytes int
	Shell           string
	Prompt          string
	FailOnError     bool
	FlushTimeout    time.Duration
	SecretNames     []string
	SecretPrefixes  []string
	SecretSuffixes  []string
}

// stringListFlag implements flag.Value for a repeatable string flag like:
//
//	-c "echo hi" -c "pwd"
//
// The standard flag package does not provide a built-in "repeatable string"
// type, so we add this tiny adapter.
type stringListFlag []string

func (s *stringListFlag) String() string {
	return strings.Join(*s, ", ")
}

func (s *stringListFlag) Set(value string) error {
	// Every time -c appears, the flag package calls Set with one value.
	*s = append(*s, value)
	return nil
}

// flagOverrides keeps the raw CLI-provided values so they can be applied after
// config files and environment variables have been loaded.
type flagOverrides struct {
	ConfigFile      string
	LogFile         string
	ReplayLogFile   string
	SyslogTarget    string
	SyslogTag       string
	QueueSize       int
	MaxCaptureBytes int
	Shell           string
	Prompt          string
	FailOnError     bool
	FlushTimeout    time.Duration
	SecretNames     string
	SecretPrefixes  string
	SecretSuffixes  string
}

// parseArgs translates raw CLI arguments into a typed config plus the chosen
// execution mode inputs.
//
// Configuration precedence is:
// 1. built-in defaults
// 2. YAML config file
// 3. PIPERY_* environment variables
// 4. CLI flags
func parseArgs(args []string, output io.Writer) (config, []string, []string, bool, error) {
	cfg := defaultConfig()

	var commands stringListFlag
	var replayFiles stringListFlag
	overrides := flagOverrides{}
	flags := flag.NewFlagSet("psh", flag.ContinueOnError)

	// We suppress the flag package's default output because we want to control
	// the help/error text ourselves and keep it consistent.
	flags.SetOutput(io.Discard)
	flags.Var(&commands, "c", "run a shell command (repeatable)")
	flags.Var(&replayFiles, "replay", "replay and compare a pipery JSONL run log (repeatable)")
	flags.StringVar(&overrides.ConfigFile, "config", "", "path to a YAML config file")
	flags.StringVar(&overrides.LogFile, "log-file", "", "path to the JSONL log file")
	flags.StringVar(&overrides.ReplayLogFile, "replay-log-file", "", "path to the JSONL log file generated by replay mode")
	flags.StringVar(&overrides.SyslogTarget, "syslog", "", "network syslog target, for example udp://127.0.0.1:514")
	flags.StringVar(&overrides.SyslogTag, "syslog-tag", "", "app tag to embed in syslog messages")
	flags.IntVar(&overrides.QueueSize, "queue-size", 0, "size of the async log queue")
	flags.IntVar(&overrides.MaxCaptureBytes, "max-capture-bytes", 0, "maximum bytes captured per stdin/stdout/stderr field")
	flags.StringVar(&overrides.Shell, "shell", "", "shell used for -c commands and REPL execution")
	flags.StringVar(&overrides.Prompt, "prompt", "", "interactive prompt")
	flags.BoolVar(&overrides.FailOnError, "fail-on-error", false, "stop the session when a command exits non-zero")
	flags.DurationVar(&overrides.FlushTimeout, "flush-timeout", 0, "maximum time to wait for async log flushing on exit")
	flags.StringVar(&overrides.SecretNames, "secret-names", "", "comma-separated env var names to always mask in logs")
	flags.StringVar(&overrides.SecretPrefixes, "secret-prefixes", "", "comma-separated env var prefixes to mask in logs")
	flags.StringVar(&overrides.SecretSuffixes, "secret-suffixes", "", "comma-separated env var suffixes to mask in logs")

	if err := flags.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			fmt.Fprint(output, usageText(cfg.Shell))
			return cfg, nil, nil, true, nil
		}
		return cfg, nil, nil, false, err
	}

	var err error
	cfg, err = loadConfig(overrides.ConfigFile)
	if err != nil {
		return cfg, nil, nil, false, err
	}

	applyFlagOverrides(flags, &cfg, overrides)
	if len(replayFiles) > 0 {
		cfg.ReplayFiles = append([]string(nil), replayFiles...)
	}

	// These validation checks keep invalid config from reaching deeper layers
	// where the failure would be harder to understand.
	if cfg.QueueSize < 1 {
		return cfg, nil, nil, false, errors.New("psh: -queue-size must be at least 1")
	}

	if cfg.MaxCaptureBytes < 0 {
		return cfg, nil, nil, false, errors.New("psh: -max-capture-bytes must be zero or greater")
	}

	if cfg.FlushTimeout < 0 {
		return cfg, nil, nil, false, errors.New("psh: -flush-timeout must be zero or greater")
	}

	directCommand := flags.Args()
	if len(cfg.ReplayFiles) > 0 {
		if len(commands) > 0 || len(directCommand) > 0 {
			return cfg, nil, nil, false, errors.New("psh: replay mode cannot be combined with -c commands or a direct command")
		}
		return cfg, nil, nil, false, nil
	}

	if len(commands) > 0 && len(directCommand) > 0 {
		// Mixing the two modes is ambiguous, so we reject it early.
		return cfg, nil, nil, false, errors.New("psh: use either repeated -c commands or a direct command after --, not both")
	}

	return cfg, commands, directCommand, false, nil
}

// defaultConfig is the built-in configuration used when the user does not
// provide any file, environment variables, or flags.
func defaultConfig() config {
	return config{
		LogFile:         "pipery.jsonl",
		ReplayLogFile:   "",
		ReplayFiles:     nil,
		SyslogTag:       "psh",
		QueueSize:       256,
		MaxCaptureBytes: 256 * 1024,
		Shell:           defaultShell(),
		Prompt:          "psh> ",
		FailOnError:     false,
		FlushTimeout:    3 * time.Second,
		SecretNames:     nil,
		SecretPrefixes:  nil,
		SecretSuffixes:  nil,
	}
}

// loadConfig reads config values from an optional YAML file and PIPERY_*
// environment variables.
//
// If no explicit config file is provided, we only look for
// ./.pipery/config.yaml and simply continue if it does not exist.
func loadConfig(configFile string) (config, error) {
	cfg := defaultConfig()
	v := viper.New()

	v.SetEnvPrefix("PIPERY")
	v.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
	v.AutomaticEnv()
	setViperDefaults(v, cfg)

	if configFile != "" {
		v.SetConfigFile(configFile)
	} else {
		discoveredConfig, err := discoverDefaultConfigFile(".")
		if err != nil {
			return cfg, err
		}
		if discoveredConfig != "" {
			v.SetConfigFile(discoveredConfig)
		}
	}

	if v.ConfigFileUsed() != "" || configFile != "" {
		if err := v.ReadInConfig(); err != nil {
			var missing viper.ConfigFileNotFoundError
			if configFile != "" || !errors.As(err, &missing) {
				return cfg, err
			}
		} else {
			if resolved, err := filepath.Abs(v.ConfigFileUsed()); err == nil {
				cfg.ConfigFile = resolved
			} else {
				cfg.ConfigFile = v.ConfigFileUsed()
			}
		}
	}

	cfg.LogFile = v.GetString("log_file")
	cfg.ReplayLogFile = v.GetString("replay_log_file")
	cfg.ReplayFiles = readStringList(v, "replay_files")
	cfg.SyslogTarget = v.GetString("syslog")
	cfg.SyslogTag = v.GetString("syslog_tag")
	cfg.QueueSize = v.GetInt("queue_size")
	cfg.MaxCaptureBytes = v.GetInt("max_capture_bytes")
	cfg.Shell = v.GetString("shell")
	cfg.Prompt = v.GetString("prompt")
	cfg.FailOnError = v.GetBool("fail_on_error")
	cfg.FlushTimeout = v.GetDuration("flush_timeout")
	cfg.SecretNames = readStringList(v, "secret_names")
	cfg.SecretPrefixes = readStringList(v, "secret_prefixes")
	cfg.SecretSuffixes = readStringList(v, "secret_suffixes")

	if cfg.ConfigFile == "" && configFile != "" {
		if resolved, err := filepath.Abs(configFile); err == nil {
			cfg.ConfigFile = resolved
		} else {
			cfg.ConfigFile = configFile
		}
	}

	return cfg, nil
}

// setViperDefaults registers the application's built-in defaults with viper.
func setViperDefaults(v *viper.Viper, cfg config) {
	v.SetDefault("log_file", cfg.LogFile)
	v.SetDefault("replay_log_file", cfg.ReplayLogFile)
	v.SetDefault("replay_files", cfg.ReplayFiles)
	v.SetDefault("syslog", cfg.SyslogTarget)
	v.SetDefault("syslog_tag", cfg.SyslogTag)
	v.SetDefault("queue_size", cfg.QueueSize)
	v.SetDefault("max_capture_bytes", cfg.MaxCaptureBytes)
	v.SetDefault("shell", cfg.Shell)
	v.SetDefault("prompt", cfg.Prompt)
	v.SetDefault("fail_on_error", cfg.FailOnError)
	v.SetDefault("flush_timeout", cfg.FlushTimeout.String())
	v.SetDefault("secret_names", cfg.SecretNames)
	v.SetDefault("secret_prefixes", cfg.SecretPrefixes)
	v.SetDefault("secret_suffixes", cfg.SecretSuffixes)
}

// applyFlagOverrides only copies flags that the user explicitly set. This keeps
// zero values from accidentally wiping out config file or environment values.
func applyFlagOverrides(flags *flag.FlagSet, cfg *config, overrides flagOverrides) {
	flags.Visit(func(currentFlag *flag.Flag) {
		switch currentFlag.Name {
		case "config":
			cfg.ConfigFile = overrides.ConfigFile
		case "log-file":
			cfg.LogFile = overrides.LogFile
		case "replay-log-file":
			cfg.ReplayLogFile = overrides.ReplayLogFile
		case "syslog":
			cfg.SyslogTarget = overrides.SyslogTarget
		case "syslog-tag":
			cfg.SyslogTag = overrides.SyslogTag
		case "queue-size":
			cfg.QueueSize = overrides.QueueSize
		case "max-capture-bytes":
			cfg.MaxCaptureBytes = overrides.MaxCaptureBytes
		case "shell":
			cfg.Shell = overrides.Shell
		case "prompt":
			cfg.Prompt = overrides.Prompt
		case "fail-on-error":
			cfg.FailOnError = overrides.FailOnError
		case "flush-timeout":
			cfg.FlushTimeout = overrides.FlushTimeout
		case "secret-names":
			cfg.SecretNames = splitCSV(overrides.SecretNames)
		case "secret-prefixes":
			cfg.SecretPrefixes = splitCSV(overrides.SecretPrefixes)
		case "secret-suffixes":
			cfg.SecretSuffixes = splitCSV(overrides.SecretSuffixes)
		}
	})
}

func readStringList(v *viper.Viper, key string) []string {
	values := v.GetStringSlice(key)
	if len(values) == 0 {
		values = []string{v.GetString(key)}
	}

	normalized := make([]string, 0, len(values))
	for _, value := range values {
		normalized = append(normalized, splitCSV(value)...)
	}

	if len(normalized) == 0 {
		return nil
	}

	return normalized
}

func splitCSV(value string) []string {
	if strings.TrimSpace(value) == "" {
		return nil
	}

	parts := strings.Split(value, ",")
	normalized := make([]string, 0, len(parts))
	for _, part := range parts {
		trimmed := strings.TrimSpace(part)
		if trimmed == "" {
			continue
		}
		normalized = append(normalized, trimmed)
	}

	if len(normalized) == 0 {
		return nil
	}

	return normalized
}

// discoverDefaultConfigFile checks the default repo-local config path we
// support, instead of letting viper guess based on the basename alone.
//
// That matters because the repo also creates files like `pipery.jsonl`, and we
// do not want to accidentally parse those as configuration.
func discoverDefaultConfigFile(dir string) (string, error) {
	candidates := []string{
		filepath.Join(dir, ".pipery", "config.yaml"),
	}

	for _, candidate := range candidates {
		info, err := os.Stat(candidate)
		if err == nil {
			if info.IsDir() {
				return "", fmt.Errorf("psh: config path %q is a directory, expected a file", candidate)
			}
			return candidate, nil
		}
		if !errors.Is(err, os.ErrNotExist) {
			return "", err
		}
	}

	return "", nil
}

// usageText builds the help text shown for -h / -help.
func usageText(shell string) string {
	return fmt.Sprintf(`psh mediates shell commands and records structured execution logs.

Usage:
  psh
  echo "echo Hi" | psh
  psh -config ./.pipery/config.yaml
  psh -c "echo hello"
  psh -c "cd /tmp" -c "pwd"
  psh -- ls -la
  psh -replay pipery.jsonl
  psh -replay run1.jsonl -replay run2.jsonl

Modes:
  No command arguments starts a line-oriented REPL.
  Piped stdin runs each incoming line as a command.
  Repeated -c runs shell commands sequentially.
  Arguments after -- execute a program directly.
  Repeated -replay validates prior JSONL logs, reruns the sequence, and compares outputs and timings.

Logging:
  Logs are written asynchronously as JSON lines.
  The default file sink is ./pipery.jsonl.
  Replay mode writes a fresh log to -replay-log-file or auto-creates <input>.N.
  Add -syslog udp://host:514 or -syslog tcp://host:514 to mirror logs to syslog.
  Config can also come from ./.pipery/config.yaml and PIPERY_* environment variables.
  Secret masking can be extended with secret names, prefixes, and suffixes.
  Enable -fail-on-error to stop after the first non-zero command result.

Interactive built-ins:
  cd [dir]
  pwd
  export KEY=VALUE
  unset KEY
  exit [code]
  quit [code]

Defaults:
  shell: %s
  env prefix: PIPERY_
`, shell)
}
